# Generated by Django 6.1.2 on 2026-10-07 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_url', models.URLField(default='https://ee-eu.kobotoolbox.org/x/NYkgOz8F', verbose_name='Kobo / Enketo form link')),
                ('allow_submit', models.BooleanField(default=False, help_text='Off = Submit only does a full check run; nothing is ever sent to Kobo.', verbose_name='Allow real submission')),
                ('headless', models.BooleanField(default=True, verbose_name='Run browser hidden')),
                ('slow_mo', models.PositiveIntegerField(default=0, verbose_name='Slow-motion delay (ms)')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=20)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('filling', 'Checking…'), ('ready', 'Ready to submit'), ('review', 'Needs review'), ('submitting', 'Submitting…'), ('submitted', 'Submitted'), ('dry_run', 'Checked (submission off)'), ('submit_failed', 'Submit failed'), ('error', 'Error')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('screenshot', models.CharField(blank=True, max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='filler.job')),
            ],
            options={
                'ordering': ['row_no'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('header', models.TextField()),
                ('question', models.TextField()),
                ('instance', models.PositiveIntegerField(default=0)),
                ('value', models.TextField(blank=True)),
                ('excel_value', models.TextField(blank=True)),
                ('suggestion', models.TextField(blank=True)),
                ('flags', models.JSONField(default=list)),
                ('note', models.TextField(blank=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('status', models.TextField(blank=True)),
                ('kind', models.CharField(blank=True, max_length=20)),
                ('options', models.JSONField(default=list)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='filler.row')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
